# Generated by Django 5.2.6 on 2025-09-24 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cyber_hours', models.FloatField(default=0)),
                ('english_hours', models.FloatField(default=0)),
                ('star', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('year', models.IntegerField(default=2025)),
                ('name', models.CharField(max_length=50)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='tracker.day')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_notes', to='tracker.day')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='images/')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracker.day')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracker.day')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('stars', models.IntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.month')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.week'),
        ),
    ]
